config/routes.rb
Rails.application.routes.draw do
  concern :toggle do
    post 'toggle', on: :member
  end

  concern :check do
    post 'check', on: :collection
  end

  resources :artists, only: %i[update destroy]

  scope '(:locale)', constraints: { locale: /ru|en/ } do
    root 'index#index'

    resources :artists, except: %i[update destroy], concerns: :check

    namespace :admin do
      resources :artists, only: %i[index show], concerns: :toggle
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# frozen_string_literal: true

# Artist
#
# Attributes:
#   - birthday [Date], optional
#   - description [Text], optional
#   - image []
#   - language_id [Language]
#   - lead [String], optional
#   - name [String]
#   - patronymic [String], optional
#   - surname [String]
class Artist < ApplicationRecord
  include Checkable
  include Toggleable

  DESCRIPTION_LIMIT = 65_535
  LEAD_LIMIT        = 255
  NAME_LIMIT        = 50

  toggleable :visible

  belongs_to :language

  validates_presence_of :name, :surname
  validates_length_of :description, maximum: DESCRIPTION_LIMIT
  validates_length_of :lead, maximum: LEAD_LIMIT
  validates_length_of :name, maximum: NAME_LIMIT
  validates_length_of :patronymic, maximum: NAME_LIMIT
  validates_length_of :surname, maximum: NAME_LIMIT

  scope :for_language, ->(v) { where(language: v) }
  scope :visible, -> { where(visible: true) }
  scope :ordered_by_surname, -> { order('surname asc, name asc') }
  scope :list_for_visitors, -> { visible.ordered_by_surname }
  scope :list_for_administration, -> { ordered_by_surname }

  def self.entity_parameters
    %i[birthday description image language_id lead name patronymic surname]
  end
end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Biovision::Base::PrivilegeMethods

  def default_url_options
    params.key?(:locale) ? { locale: I18n.locale } : {}
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<% content_for :meta_title, 'О проекте' %>
<% content_for :breadcrumbs do %>
  <span><%= t('.nav_text') %></span>
<% end %>

<article>
  <h1>О проекте «Искусство. От А до Я»</h1>

  <p>
    Интернет изменил не только способ создания искусства, но также и форму его
    использования и восприятия. Когда путешествуешь по всемирной паутине,
    неизбежно сталкиваешься с сайтами, у которых есть заманчивые предложения
    художникам, которые предлагают информацию о ярких, порой скандальных,
    шокирующих явлениях в сфере современного искусства и о многочисленных
    и разнообразных выставках в мире. Или предоставляют серию банков данных
    такого типа (artnet.com): более 400 000 художников, работающих с IV века
    до наших дней, проявивших себя в различных дисциплинах и стилях
    (рисунок – акварель, живопись, графика, скульптура, фотография
    и аудиовизуальные и мультимедийные средства). Это любопытно и познавательно,
    но цели сайта «От А до Я» иные.
  </p>

  <p>
    Мы не стремимся гнаться за «свежатинкой» или предоставлять информацию
    исключительно о новых выставках в мире. Главная наша задача – погрузить
    зрителей в самую суть происходящих в современном искусстве процессов
    и познакомить зрителей с тем, что происходит внутри него: как работает
    система современного искусства с её важнейшими игроками (художники, критики,
    кураторы, коллекционеры, музеи, галереи, арт рынок…). А каков инструментарий
    современного художника (методы, принципы, стратегии, формы, техники)?
    Целесообразно также подготовить материалы, рассказывающие о своеобразии
    современного искусства, о том, как оно функционирует, какие формы,
    материалы, техники использует, каким стилям отдаёт предпочтение.
  </p>

  <p>
    Чрезвычайно любопытно проанализировать, в чём новаторство современного
    искусства и обращается ли оно к традициям. Необходимо подробно остановиться
    и на новых формах, жанрах, видах современного искусства – инсталляции,
    граффити, street art – и попытаться понять, как они функционируют, почему
    многие художники отдают им предпочтение?
  </p>

  <p>
    Важное значение имеет и вопрос об идентичности произведения. Что позволяет
    назвать определённый предмет, объект, ситуацию, процесс произведением
    искусства? И как функционируют сегодня галереи современного искусства?
    Это лаборатории или магазины?
  </p>

  <p>
    Хотелось бы сделать сайт «От А до Я» трибуной для высказывания художников
    на различные темы, связанные с искусством. Само название сайта предполагает
    полноценный и максимально исчерпывающий поиск свежих идей в творчестве
    и их обсуждение. Причём в очень своеобразной форме. Предлагается тема.
    Например, вторжение. Возможно, как комментарий к происходящему в мире,
    в котором мы живём, когда подвергаемся бомбардировке лишённой фильтрации
    информации. Как отвечает на эти вызовы художник? Иногда он даже обращается
    к текстам, документам, земле, воде… Или другая тема - аккумуляция,
    повторение, одержимость и роль архивов. Или: творческий процесс сегодня.
    Неожиданные повороты.
  </p>

  <p>
    Предполагаемые рубрики: Новости. Выставки. Тенденции. Аукционы. Премии.
    Форум. Интервью. События. Аукционы. Срочно.
  </p>

  <p>
    И, конечно, мы будем информировать посетителей о ярких выставках,
    прежде всего зарубежных, о самых дорогих художниках в мире, топ лотах
    на аукционах, необычных проектах. Предполагаются также интервью
    с художниками, критиками, коллекционерами, кураторами.  Помимо этого,
    вас ждут курьёзы и любопытные вещи.
  </p>

  <footer>
    Витория Хан-Магомедова,<br/>
    Главный редактор.
  </footer>
</article>

app/views/admin/users/entity/_custom_nav.html.erb
<!--
Здесь можно задать дополнительные пункты для навигации на странице пользователя
в админке. Экземпляр просматриваемого пользователя находится в entity
-->

app/views/index/index.html.erb
<% if @editable_page.nil? %>
  <% content_for :meta_title, t('.title') %>
  <% content_for :meta_description, t('.description') %>
<% else %>
  <%= render partial: 'editable_pages/entity/metadata', locals: { entity: @editable_page } %>
<% end %>

<article id="homepage">
  <%= render partial: 'index/index/editable', locals: { entity: @editable_page } %>
  <%= render 'index/index/default_dashboard' %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= locale %>" prefix="og: http://ogp.me/ns#">
<head>
  <meta charset="UTF-8"/>
  <title><%= yield :meta_title %></title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <meta name="format-detection" content="telephone=no"/>
  <%= yield :alternate_links %>
  <%= render 'shared/meta_texts' %>
  <%= render 'shared/favicons' %>
</head>
<body>
<%= render 'layouts/application/header' %>

<main id="main">
  <%= render 'shared/flash_messages' %>
  <%= render 'shared/breadcrumbs' %>

  <%= yield %>
</main>

<%= render 'layouts/application/footer' %>
<%= raw SimpleBlock['counters'] %>
</body>
</html>

app/views/layouts/application/_footer.html.erb
<footer id="main-footer">
  <div>
    <div class="copyright">&copy; <%= t(:copyright) %></div>
    <nav>
      <ul>
        <li><%= link_to(t('about.index.nav_text'), about_path) %></li>
<!--        <li><%#= link_to(t('about.tos.nav_text'), tos_path) %></li>-->
<!--        <li><%#= link_to(t('about.privacy.nav_text'), privacy_path) %></li>-->
        <% if UserPrivilege.user_has_any_privilege?(current_user) %>
            <li><%= link_to(t('admin.index.index.heading'), admin_path) %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/application/_header.html.erb
<header id="main-header">
  <div>
    <div class="logo">
      <%= link_to(image_tag('logo.svg', alt: 'А–Я'), root_path) %>
    </div>
    <div class="title">Современное искусство. Теория и практика.</div>
    <nav>
      <%= render 'layouts/application/header/navigation' %>
    </nav>
    <%= render 'layouts/application/header/authentication' %>
  </div>
</header>

app/views/shared/_favicons.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">